# Generated by Django 2.0.2 on 2018-04-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=30)),
                ('descripcio', models.CharField(max_length=600)),
                ('date', models.DateField()),
                ('num_stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='anunci',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuari'),
        ),
    ]
