# Generated by Django 2.0.2 on 2018-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='email',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
