# Generated by Django 2.0.2 on 2018-04-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usuari_email'),
        ('home', '0002_valors'),
    ]

    operations = [
    ]
