# Generated by Django 2.0.2 on 2018-04-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_20180415_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='valors',
        ),
        migrations.AlterField(
            model_name='anunci',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuari',
        ),
    ]
